org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.1
minecraft_version_range=[26.1,)
neo_version=26.1.0.1-beta
mod_id=minecraftuuuum
mod_name=Minecraftuuuum!
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.minecraftuuuum
mod_authors=Minecraftuuuum
mod_description=Textual lemma prompts for Minecraft mods.
