plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = '0.1.0'
group = 'com.minecraftuuuum'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = '26.1.0.1-beta'
    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }
    mods {
        minecraftuuuum {
            sourceSet sourceSets.main
        }
    }
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : '26.1',
            minecraft_version_range: '[26.1,)',
            neo_version            : '26.1.0.1-beta',
            mod_id                 : 'minecraftuuuum',
            mod_name               : 'Minecraftuuuum!',
            mod_license            : 'MIT',
            mod_version            : '0.1.0',
            mod_description        : 'Textual lemma prompts for Minecraft mods.'
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
